version: '2'
services:
  vrouter-cni:
    image: "{{ container_registry }}/contrail-kubernetes-cni-init:{{ contrail_version_tag }}"
    network_mode: "host"
    volumes:
      - /var/lib/contrail:/var/lib/contrail
      - /etc/cni:/host/etc_cni
      - /opt/cni/bin:/host/opt_cni_bin
      - /var/log/contrail/cni:/var/log/contrail/cni
