options:
  cluster_name:
    type: string
    default: k8s
    decription: |
      Kubernetes cluster name
  cluster_project:
    type: string
    default: "{}"
    description: |
      Kubernetes cluster project
  cluster_network:
    type: string
    default: "{}"
    description: |
      Kubernetes cluster network
  pod_subnets:
    type: string
    default: "10.32.0.0/12"
    description: |
      Kubernetes pod subnets
  ip_fabric_subnets:
    type: string
    default: "10.64.0.0/12"
    description: |
      Kubernetes IP fabric subnets
  service_subnets:
    type: string
    default: "10.96.0.0/12"
    description: |
      Kubernetes service subnets
  ip_fabric_forwarding:
    type: boolean
    default: false
    description: |
      Kubernetes IP fabric forwarding
  ip_fabric_snat:
    type: boolean
    default: true
    description: |
      Kubernetes IP fabric snat
  host_network_service:
    type: boolean
    default: false
    description: |
      Kubernetes host network service
  public_fip_pool:
    type: string
    default: "{}"
    description: |
      Kubernetes public floating IP pool

  kubernetes_api_hostname:
    type: string
    description: |
      Virtual IP or hostname to access to Kubernetes Cluster API
  kubernetes_api_secure_port:
    type: string
    description: |
      Secure port to access a Kubernetes Cluster API

  log-level:
    type: string
    default: SYS_NOTICE
    description: |
      Log level for contrail services. Valid values are:
      SYS_EMERG, SYS_ALERT, SYS_CRIT, SYS_ERR, SYS_WARN, SYS_NOTICE, SYS_INFO, SYS_DEBUG
  docker_runtime:
    type: string
    default: upstream
    description: |
      Docker runtime to install valid values are "upstream" (Docker PPA), "apt" (Ubuntu archive),
      "auto" (Ubuntu archive), or "custom" (must have set `docker_runtime_repo` URL,
      `docker_runtime_key_url` URL and `docker_runtime_package` name).
  docker_runtime_key_url:
    type: string
    description: |
      Custom Docker repository validation key URL.
  docker_runtime_package:
    type: string
    description: |
      Custom Docker repository package name.
  docker_runtime_repo:
    type: string
    description: |
      Custom Docker repository, given in deb format. Use `{ARCH}` to determine architecture at runtime.
      Use `{CODE}` to set release codename.
      E.g. `deb [arch={ARCH}] https://download.docker.com/linux/ubuntu {CODE} stable`.
  docker-registry:
    type: string
    default: opencontrailnightly
    description: |
      URL of docker-registry
  docker-registry-insecure:
    type: boolean
    default: false
    description: |
      Is it docker-registry insecure and should docker be configured for it
  docker-user:
    type: string
    description: |
      Login to the docker registry.
  docker-password:
    type: string
    description: |
      Password to the docker registry.
  image-tag:
    type: string
    default: latest
    description: |
      Tag of docker image.
  http_proxy:
    type: string
    default: ""
    description: |
      URL to use for HTTP_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
  https_proxy:
    type: string
    default: ""
    description: |
      URL to use for HTTPS_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
  no_proxy:
    type: string
    default: ""
    description: |
      Comma-separated list of destinations (either domain names or IP
      addresses) that should be directly accessed, by opposition of going
      through the proxy defined above. Must be less than 2023 characters long

  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
