options:
  control-network:
    type: string
    description: |
      The IP address and netmask of the control network (e.g. 192.168.0.0/24).
      This network will be used for Contrail endpoints.
      If not specified, default network will be used.
  log-level:
    type: string
    default: SYS_NOTICE
    description: |
      Log level for contrail services. Valid values are:
      SYS_EMERG, SYS_ALERT, SYS_CRIT, SYS_ERR, SYS_WARN, SYS_NOTICE, SYS_INFO, SYS_DEBUG
  docker-registry:
    type: string
    default: opencontrailnightly
    description: |
      URL of docker-registry
  docker-registry-insecure:
    type: boolean
    default: false
    description: |
      Is it docker-registry insecure and should docker be configured for it
  docker-user:
    type: string
    description: |
      Login to the docker registry.
  docker-password:
    type: string
    description: |
      Password to the docker registry.
  image-tag:
    type: string
    default: latest
    description: |
      Tag of docker image.
