options:
  install-sources:
    type: string
    description: Package sources for install
  install-keys:
    type: string
    description: Apt keys for package install sources
  enable-metadata-server:
    type: boolean
    default: true
    description: |
      Configures metadata shared secret and tells nova to run a local instance
      of nova-api-metadata for serving metadata to VMs.
  use-internal-endpoints:
    type: boolean
    default: False
    description: |
      Openstack mostly defaults to using public endpoints for internal
      communication between services. If set to True this option will
      configure services to use internal endpoints where possible.
