options:
  multi_tenancy:
    type: boolean
    default: True
    description: |
      Enable or disable multi_tenancy - True/False.
      The effects of setting this are:
      1. multi_tenancy for config_api is enabled/disabled
      2. static_auth is used in webui in case of multi_tenancy disabled
