options:
  auth-mode:
    type: string
    default: rbac
    description: |
      'rbac', 'cloud-admin' or 'no-auth'
      Authentication mode. Detailed information can be found in the Contrail documentation.
  cloud-admin-role:
    type: string
    default: admin
    description: |
      Role name in keystone for users that have full access to everything.
  global-read-only-role
    type: string
    default: guest
    description: |
      Role name in keystone for users that have read-only access to everything.
