options:
  auth-mode:
    type: string
    default: cloud-admin
    description: |
      It represents 'aaa_mode' configuration key of Contrail.
      Can be one of: 'rbac', 'cloud-admin' or 'no-auth'
      Authentication mode. Detailed information can be found in the Contrail documentation.
  cloud-admin-role:
    type: string
    default: admin
    description: |
      Role name in keystone for users that have full access to everything.
  global-read-only-role:
    type: string
    description: |
      Role name in keystone for users that have read-only access to everything.
  ssl_cert:
    type: string
    default:
    description: |
      SSL certificate to install and use for API ports.
  ssl_key:
    type: string
    default:
    description: SSL key to use with certificate specified as ssl_cert.
  ssl_ca:
    type: string
    default:
    description: |
      SSL CA to use with the certificate and key provided - this is only
      required if you are providing a privately signed ssl_cert and ssl_key.
