contrail-tsn:
  tor-switches: |
   [
    {
       tor_ip: 193.168.1.3,
       tor_agent_id: 1,
       tor_ovs_port: 6632,
       tor_tunnel_ip: 7.7.7.7,
       tsn_ip: 192.168.1.29,
       tor_ovs_protocol: pssl,
       tor_tsn_name: "ComputeNode3",
       tor_name: "b3-qfx1",
       tor_vendor_name: "Juniper",
       tor_product_name: "QFX5100",
       tor_agent_http_server_port: 9010
    }
   ]
