options:
  remove-juju-bridge:
    type: boolean
    default: true
    description: |
      Juju on MAAS creates bridges for deploying LXD/LXC and KVM workloads.
      Enable this to remove such a bridge if you want to install vhost0 directly
      on the underlying interface.
  cloud_orchestrator:
    type: string
    default: openstack
    description: |
      cloud_orchestrator - what cloud orchestrator is being used. Valid
      options are kubernetes, openstack, mesos.
