version: '2'
services:
  web:
    image: "{{ container_registry }}/contrail-controller-webui-web:{{ contrail_version_tag }}"
    network_mode: "host"
    env_file: /etc/contrail/common_config.env
    volumes:
      - /var/log/contrail:/var/log/contrail
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/crashes:/var/crashes
      - /etc/contrail/ssl:/etc/contrail/ssl
    restart: always
  job:
    image: "{{ container_registry }}/contrail-controller-webui-job:{{ contrail_version_tag }}"
    network_mode: "host"
    env_file: /etc/contrail/common_config.env
    volumes:
      - /var/log/contrail:/var/log/contrail
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/crashes:/var/crashes
      - /etc/contrail/ssl:/etc/contrail/ssl
    restart: always
